#!/usr/bin/env bash

# Bootstraps all nodes except the mgmt node.

# Deletes all present authorized keys
rm -rf /home/vagrant/.ssh/authorized_keys/*

# Installs the SSH key generated by the mgmt node
cat /vagrant/common_files/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys && echo "Syncing mgmt's public key with $HOSTNAME."
chown -R vagrant:vagrant /home/vagrant/
