# Define the virtual environment
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'
require 'fileutils'

Vagrant.configure("2") do |config|

  # Load the node definitions YAML file
  nodes = YAML.load_file('nodes.yml')

  # Delete the generated files if present
  FileUtils.rm_f('ansible/roles/common/files/hosts.system')
  FileUtils.rm_f('ansible/roles/utility/files/hosts.ansible')

  # Create clones of the prototype files
  FileUtils.cp('common_files/hosts.system.proto', 'common_files/hosts.system')
  FileUtils.cp('mgmt_files/hosts.ansible.proto', 'mgmt_files/hosts.ansible')

  # Put the header messages to the newly created hosts files
  headerMessage = '# [' + Time.now.strftime("%Y-%m-%d %H:%M:%S").to_s + '] Generated by Envy (https://github.com/notty-daemon/envy)'
  open('common_files/hosts.system', 'a') { |f| f.puts ''; f.puts headerMessage }
  open('mgmt_files/hosts.ansible', 'a') { |f| f.puts ''; f.puts headerMessage }

  # Iterate through all nodes to add their information to the hosts files
  nodes.each do |nodes|
    # Generate the system's hosts file for use on all nodes.
    open('common_files/hosts.system', 'a') { |f|
      f.puts nodes['ip'] + ' ' + nodes['host']
    }

    # Generate the Ansible hosts file for use on the mgmt node.
    open('mgmt_files/hosts.ansible', 'a') { |f|
      f.puts nodes['host']
    }
  end

  # Configure the common nodes
  nodes.each do |nodes|
    config.vm.define nodes['host'] do |nodeConfiguration|
      nodeConfiguration.vm.box = "ubuntu/trusty64"
      nodeConfiguration.vm.hostname = nodes['host']
      nodeConfiguration.vm.network :private_network, ip: nodes['ip']
      nodeConfiguration.vm.provider "virtualbox" do |vb|
        vb.memory = nodes['mem']
      end
      nodeConfiguration.vm.provision :shell, path: "bootstrap-common.sh"
    end
  end

  # Configure the utility node (Ansible management node)
  config.vm.define :mgmt do |mgmt_config|
    mgmt_config.vm.box = "ubuntu/trusty64"
    mgmt_config.vm.hostname = "mgmt"
    mgmt_config.vm.network :private_network, ip: "192.168.10.100"
    mgmt_config.vm.provider "virtualbox" do |vb|
        vb.memory = "256"
    end
    mgmt_config.vm.provision :shell, path: "bootstrap-mgmt.sh"
    mgmt_config.vm.provision :shell, inline: "export HOME='/home/vagrant/'; sudo -u vagrant ansible-playbook /home/vagrant/ansible/installation.yml"
  end
end
